services:
  web:
    build: .
    command: npm run start:prod
    volumes:
      - /usr/src/app
    environment:
      DB_HOST: "maestria-moviles-oukcew-db"
      DB_USER: "postgres"
      DB_PASS: "postgres"
      DB_NAME: "vinyls"
      USE_SSL: "false"
    expose:
      - 3000
    depends_on:
      - db
    links:
      - db


  db:
    image: postgres
    environment:
      - POSTGRES_DB=vinyls
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    volumes:
      - "../files/pgdata:/var/lib/postgresql/data/"
    networks:
      - dokploy-network
